<?php

namespace Database\Seeders;

use App\Models\Project;
use App\Models\SubProject;
use Illuminate\Support\Str;
use Illuminate\Database\Seeder;

class ProjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //

        //project seeder is start here
        $project = [
            
            [     

                'title' =>'LAHORE',
                'slug' => Str::slug('LAHORE'),
                'description' => 'The Need of the Current Hour<br>
                Real estate projects are all the new rage because of the issues of overpopulation. People tend to reside in a city that promises amenities that are in close proximity and easy to access. Lahore is a city that offers the best possible educational institutes as well as profitable real investment avenues. That is why people prefer to find residential and commercial plots in this "city of gardens".<br>
                
                A Promise of Green Living<br>
                All these projects promise the quality of life embroiled with the right dose of sustainability. These Lahore projects are not only a symbol of class but also solidifies the importance of quality living and urban vision. These real estate projects in Lahore are the best possible ventures of investment as they are also a great means of standard living. Customers should keep their eyes on these impeccable projects by the top real estate companies because they are in for a treat.<br>
                
                Investing in these projects ensures both better living standards and promising revenue.<br>
                
                These projects are state of the art and bring a sense of elegance to the artistic vibe of Lahore city. The futuristic designs compliment the vibe of the city so well and bring Lahore one step closer to a desirable place that everyone wants to visit.<br>
                
                The Main Agenda<br>
                The goal is to make a stylized and comfortable living a dream come true. These Lahore projects are living breathing examples of unflinching efforts of top real estate companies of Lahore. With these ambitious projects on the horizon, the future of real estate in Lahore is in the making.<br>
                
                Different Avenues for Standard Living<br>
                These variable projects ensure both commercial and residential lifestyle opportunities for the native residents. While Bahria Town promises quality of life, H & S Hotels awaken an entertaining avenue for the general public. Standard living is the basic right of humans. All these quality projects ensure the quality of life possible for the residents of Lahore.',
                'excerpt' => 'Lahore is a city of many wonders. From boasting the best educational opportunities for individuals to ensuring promising real estate investment, Lahore is a city that has it all. The sector of real estate in Lahore has witnessed the best growth in the past centuries. Some of the past Lahore projects are a clear depiction of classic architecture. But now the real estate companies in Lahore are rewriting the citys history for the greater good. With futuristic plans and top real estate companies in Lahore backing the projects, the dawn of a new and revolutionized age is in the making.',
                'status' => 1,
                'is_active' => 1,
                'order' => 1,
                'meta_title' => 'LAHORE',
                'meta_tag' => 'LAHORE',
                'image' => '1.jpg',
                'meta_description' => 'LAHORE',
            ],
        
            [     

                'title' =>'ISLAMABAD',
                'slug' => Str::slug('ISLAMABAD'),
                'description' => 'ISLAMABAD description',
                'excerpt' => 'Islamabad is a lovely city that is already highly developed. However, as the citys population grows, so does the amount of development activity and the opportunities for investors. That is why real estate projects in Islamabad have performed well in recent years and will continue to do so in the future.',
                'status' => 1,
                'is_active' => 1,
                'order' => 2,
                'meta_title' => 'ISLAMABAD',
                'meta_tag' => 'ISLAMABAD',
                'image' => '1.jpg',
                'meta_description' => 'ISLAMABAD',
            ],
            [     

                'title' =>'SIALKOT',
                'slug' => Str::slug('SIALKOT'),
                'description' => 'SIALKOT description',
                'excerpt' => 'SIALKOT excerpt',
                'status' => 1,
                'is_active' => 1,
                'order' => 3,
                'meta_title' => 'SIALKOT',
                'meta_tag' => 'SIALKOT',
                'image' => '1.jpg',
                'meta_description' => 'SIALKOT',
            ],
            [     

                'title' =>'PESHAWAR',
                'slug' => Str::slug('PESHAWAR'),
                'description' => 'PESHAWAR',
                'excerpt' => 'There is no denying the fact that Peshawar is a city of wonders. This city is rich in history and was known as the “Crown Jewel”. From being the ancient city in the subcontinent to now a potential hub of export and import, Peshawar has witnessed progressive prowess in Pakistan as no other city has.

                Like all other sectors, real estate has also been flourishing at an astonishing rate in Peshawar. All the current and past projects of real estate in this capital city of KPK speaks volume of this growth. The construction and real estate developers are thriving to revamp this niche in Peshawar and that too for both domestic and national good. With all the right ingredients in the bag, a new and revolutionized Peshawar from a real estate point of view is just around the corner.',
                'status' => 1,
                'is_active' => 1,
                'order' => 4,
                'meta_title' => 'PESHAWAR',
                'meta_tag' => 'PESHAWAR',
                'image' => '1.jpg',
                'meta_description' => 'PESHAWAR',
            ],

        ];
          

        foreach ($project as $pr) {
            Project::create($pr);
        }
        //project seeder is End here

        //Sub project seeder is start here
        $subProject = [
            //lahore projects
            [
                'project_id'=> 1,
                'title' =>'Lahore Smart City',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'Lahore Bypass near Kala Shah Kaku',
                'image' => 'lahore smart city.jpg',
                'slug' => Str::slug('Lahore Smart City'), 
                'description' => 'sad',
                'excerpt' => 'Lahore Smart City',
                'status' => 1,
                'is_active' => 1,
                'order' => 1,
                'project_type'=> 'Commercial & Residential',
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => 'Lahore Smart City',
                'meta_tag' => 'Lahore Smart City',
                'meta_description' => 'Lahore Smart City',

            ],
            [
                'project_id'=> 1,
                'title' =>'Kings Town',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'RAIWIND ROAD LAHORE',
                'image' => 'kingstown.png',
                'slug' => Str::slug('Kings Town'), 
                'description' => 'Kings Town',
                'excerpt' => 'Kings Town',
                'status' => 1,
                'is_active' => 1,
                'order' => 2,
                'project_type'=> 'commercial',
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => 'Kings Town',
                'meta_tag' => 'Kings Town',
                'meta_description' => 'Kings Town',

            ],
            [
                'project_id'=> 1,
                'title' =>'Al Kabir Town',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'RAIWIND ROAD LAHORE',
                'image' => 'ALKabirTown.jpg',
                'slug' => Str::slug('Al Kabir Town'), 
                'description' => 'Al Kabir Town',
                'excerpt' => 'Al Kabir Town',
                'status' => 1,
                'is_active' => 1,
                'order' => 3,
                'project_type'=> 'commercial',
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => 'Al Kabir Town',
                'meta_tag' => 'Al Kabir Town',
                'meta_description' => 'Al Kabir Town',

            ],
            [
                'project_id'=> 1,
                'title' =>'Liberty Land',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'Mauza Jia Bagga, Tehsil Raiwind, Lahore',
                'image' => 'libertylands.jpg',
                'slug' => Str::slug('Liberty Land'), 
                'description' => 'Liberty Land',
                'excerpt' => 'Liberty Land',
                'status' => 1,
                'is_active' => 1,
                'order' => 4,
                'project_type'=> 'commercial',
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => 'Liberty Land',
                'meta_tag' => 'Liberty Land',
                'meta_description' => 'Liberty Land',

            ],
            [
                'project_id'=> 1,
                'title' =>'Madina Heights',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'Bahria Town, Lahore',
                'image' => 'madinaheights.jpg',
                'slug' => Str::slug('Madina Heights'), 
                'description' => 'Madina Heights',
                'excerpt' => 'Madina Heights',
                'status' => 1,
                'is_active' => 0,
                'order' => 5,
                'project_type'=> 'commercial',
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => 'Madina Heights',
                'meta_tag' => 'Madina Heights',
                'meta_description' => 'Madina Heights',

            ],
            [
                'project_id'=> 1,
                'title' =>'Bahria Town',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'Bahria , Pakistan',
                'image' => 'bahria.jpg',
                'slug' => Str::slug('Bahria Town'), 
                'description' => 'Bahria Town',
                'excerpt' => 'Bahria Town',
                'status' => 1,
                'is_active' => 0,
                'order' => 6,
                'project_type'=> 'commercial',
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => 'Bahria Town',
                'meta_tag' => 'Bahria Town',
                'meta_description' => 'Bahria Town',

            ],
            [
                'project_id'=> 1,
                'title' =>'H & S Hotels',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'Liberty Market',
                'image' => 'h&s.png',
                'slug' => Str::slug('H & S Hotels'), 
                'description' => 'H & S Hotels',
                'excerpt' => 'H & S Hotels',
                'status' => 1,
                'is_active' => 1,
                'order' => 7,
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => 'H & S Hotels',
                'meta_tag' => 'H & S Hotels',
                'meta_description' => 'H & S Hotels',

            ],
            [
                'project_id'=> 1,
                'title' =>'3-Jays Tower',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'Ali Zaib road , Lahore',
                'image' => '3jaystower.jpg',
                'slug' => Str::slug('3-Jays Tower'), 
                'description' => '3-Jays Tower',
                'excerpt' => '3-Jays Tower',
                'status' => 1,
                'is_active' => 0,
                'order' => 8,
                'project_type'=> 'commercial',
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => '3-Jays Tower',
                'meta_tag' => '3-Jays Tower',
                'meta_description' => '3-Jays Tower',

            ],
            [
                'project_id'=> 1,
                'title' =>'Pace Circle',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'Ring Road Lahore',
                'image' => 'pacecircle.jpg',
                'slug' => Str::slug('Pace Circle'), 
                'description' => 'Pace Circle',
                'excerpt' => 'Pace Circle',
                'status' => 1,
                'is_active' => 0,
                'order' => 9,
                'project_type'=> 'commercial',
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => 'Pace Circle',
                'meta_tag' => 'Pace Circle',
                'meta_description' => 'Pace Circle',

            ],
            [
                'project_id'=> 1,
                'title' =>'Icon Valley Phase 2',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'Raiwind Road Lahore',
                'image' => 'iconvalley.jpg',
                'slug' => Str::slug('Icon Valley Phase 2'), 
                'description' => 'Icon Valley Phase 2',
                'excerpt' => 'Icon Valley Phase 2',
                'status' => 1,
                'is_active' => 0,
                'order' => 10,
                'project_type'=> 'commercial',
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => 'Icon Valley Phase 2',
                'meta_tag' => 'Icon Valley Phase 2',
                'meta_description' => 'Icon Valley Phase 2',

            ],
            [
                'project_id'=> 1,
                'title' =>'Dream Gardens',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'Near Shoukat Khanum Hospital',
                'image' => 'dreamgardens.jpg',
                'slug' => Str::slug('Dream Gardens'), 
                'description' => 'Dream Gardens',
                'excerpt' => 'Dream Gardens',
                'status' => 1,
                'is_active' => 1,
                'order' => 11,
                'project_type'=> 'commercial',
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => 'Dream Gardens',
                'meta_tag' => 'Dream Gardens',
                'meta_description' => 'Dream Gardens',

            ],
            [
                'project_id'=> 1,
                'title' =>'Park View City',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'Multan road Lahore',
                'image' => 'parkview.jpg',
                'slug' => Str::slug('Park View City'), 
                'description' => 'Park View City',
                'excerpt' => 'Park View City',
                'status' => 1,
                'is_active' => 1,
                'order' => 12,
                'project_type'=> 'commercial',
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => 'Park View City',
                'meta_tag' => 'Park View City',
                'meta_description' => 'Park View City',

            ],
            [
                'project_id'=> 1,
                'title' =>'Times Square',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'Bahria Orchard Phase 4',
                'image' => 'Time-squre-Mall-project-title-img.jpg',
                'slug' => Str::slug('Times Square'), 
                'description' => 'Times Square',
                'excerpt' => 'Times Square',
                'status' => 1,
                'is_active' => 1,
                'order' => 13,
                'project_type'=> 'commercial',
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => 'Times Square',
                'meta_tag' => 'Times Square',
                'meta_description' => 'Times Square',

            ],
            [
                'project_id'=> 1,
                'title' =>'Residence 15',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'Gulberg Lahore',
                'image' => 'Residence-15-project-title-img.jpg',
                'slug' => Str::slug('Residence 15'), 
                'description' => 'Residence 15',
                'excerpt' => 'Residence 15',
                'status' => 1,
                'is_active' => 0,
                'order' => 14,
                'project_type'=> 'commercial',
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => 'Residence 15',
                'meta_tag' => 'Residence 15',
                'meta_description' => 'Residence 15',

            ],
            [
                'project_id'=> 1,
                'title' =>'DB 32',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'Khayaban-e-Iqbal DHA',
                'image' => 'DB-32-project-title-img.jpg',
                'slug' => Str::slug('DB 32'), 
                'description' => 'DB 32',
                'excerpt' => 'DB 32',
                'status' => 1,
                'is_active' => 0,
                'order' => 15,
                'project_type'=> 'commercial',
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => 'DB 32',
                'meta_tag' => 'DB 32',
                'meta_description' => 'DB 32',

            ],
            [
                'project_id'=> 1,
                'title' =>'Skyscraper',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'Johar Town, Lahore',
                'image' => 'Skyscraper-project-title-img.jpg',
                'slug' => Str::slug('Skyscraper'), 
                'description' => 'Skyscraper',
                'excerpt' => 'Skyscraper',
                'status' => 1,
                'is_active' => 0,
                'order' => 16,
                'project_type'=> 'commercial',
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => 'Skyscraper',
                'meta_tag' => 'Skyscraper',
                'meta_description' => 'Skyscraper',

            ],
            [
                'project_id'=> 1,
                'title' =>'Maryam Town',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'Main Raiwind Road, Lahore',
                'image' => 'maryam-town-project-img.jpg',
                'slug' => Str::slug('Maryam Town'), 
                'description' => 'Maryam Town',
                'excerpt' => 'Maryam Town',
                'status' => 1,
                'is_active' => 0,
                'order' => 17,
                'project_type'=> 'commercial',
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => 'Maryam Town',
                'meta_tag' => 'Maryam Town',
                'meta_description' => 'Maryam Town',

            ],
            [
                'project_id'=> 1,
                'title' =>'Pearl One',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'Gulberg III, Close to MM Alam Road',
                'image' => 'Pearl-One-Residencies-Home-Image.jpg',
                'slug' => Str::slug('Pearl One'), 
                'description' => 'Pearl One',
                'excerpt' => 'Pearl One',
                'status' => 1,
                'is_active' => 0,
                'order' => 18,
                'project_type'=> 'commercial',
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => 'Pearl One',
                'meta_tag' => 'Pearl One',
                'meta_description' => 'Pearl One',

            ],
            [
                'project_id'=> 1,
                'title' =>'Etihad Town',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'Main Raiwind Road',
                'image' => 'Liberty-Land-Slider--Image_udwma7.jpg',
                'slug' => Str::slug('Etihad Town'), 
                'description' => 'Etihad Town',
                'excerpt' => 'Etihad Town',
                'status' => 1,
                'is_active' => 0,
                'order' => 19,
                'project_type'=> 'commercial',
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => 'Etihad Town',
                'meta_tag' => 'Etihad Town',
                'meta_description' => 'Etihad Town',

            ],
            //End lahore projects

            //ISLAMABAD projects
            [
                'project_id'=> 2,
                'title' =>'Capital Smart City',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'Lahore-Islamabad Motorway M-2',
                'image' => 'islamabad capital main-image.jpg',
                'slug' => Str::slug('Islamabad Capital Smart City'), 
                'description' => 'Capital Smart City',
                'excerpt' => 'Capital Smart City',
                'status' => 1,
                'is_active' => 1,
                'order' => 1,
                'project_type'=> 'commercial',
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => 'Capital Smart City',
                'meta_tag' => 'Capital Smart City',
                'meta_description' => 'Capital Smart City',

            ],
            [
                'project_id'=> 2,
                'title' =>'One Capital Residences',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'Lahore-Islamabad Motorway M-2',
                'image' => 'One-CR-Home-Image_kka9hm islamabad.jpg',
                'slug' => Str::slug('One Capital Residences'), 
                'description' => 'One Capital Residences',
                'excerpt' => 'One Capital Residences',
                'status' => 1,
                'is_active' => 0,
                'order' => 2,
                'project_type'=> 'commercial',
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => 'One Capital Residences',
                'meta_tag' => 'One Capital Residences',
                'meta_description' => 'One Capital Residences',

            ],
            [
                'project_id'=> 2,
                'title' =>'Nova City',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'Lahore-Islamabad Motorway M-2',
                'image' => 'Nova-city-Home-Image_zhc2tz islamabad.jpg',
                'slug' => Str::slug('Islamabad Nova City'), 
                'description' => 'Nova City',
                'excerpt' => 'Nova City',
                'status' => 1,
                'is_active' => 0,
                'order' => 3,
                'project_type'=> 'commercial',
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => 'Nova City',
                'meta_tag' => 'Nova City',
                'meta_description' => 'Nova City',

            ],
            [
                'project_id'=> 2,
                'title' =>'Nexus Mall',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'Lahore-Islamabad Motorway M-2',
                'image' => 'nexus islamabad.jpg',
                'slug' => Str::slug('Nexus Mall'), 
                'description' => 'Nexus Mall',
                'excerpt' => 'Nexus Mall',
                'status' => 1,
                'is_active' => 0,
                'order' => 4,
                'project_type'=> 'commercial',
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => 'Nexus Mall',
                'meta_tag' => 'Nexus Mall',
                'meta_description' => 'Nexus Mall',

            ],
            [
                'project_id'=> 2,
                'title' =>'Opal Square',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'Lahore-Islamabad Motorway M-2',
                'image' => 'opal islamabad.jpg',
                'slug' => Str::slug('Opal Square'), 
                'description' => 'Opal Square',
                'excerpt' => 'Opal Square',
                'status' => 1,
                'is_active' => 1,
                'order' => 5,
                'project_type'=> 'commercial',
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => 'Opal Square',
                'meta_tag' => 'Opal Square',
                'meta_description' => 'Opal Square',

            ],
            [
                'project_id'=> 2,
                'title' =>'Mid Mall',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'Lahore-Islamabad Motorway M-2',
                'image' => 'midmall islamabad.jpg',
                'slug' => Str::slug('Mid Mall'), 
                'description' => 'Mid Mall',
                'excerpt' => 'Mid Mall',
                'status' => 1,
                'is_active' => 0,
                'order' => 6,
                'project_type'=> 'commercial',
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => 'Mid Mall',
                'meta_tag' => 'Mid Mall',
                'meta_description' => 'Mid Mall',

            ],
            [
                'project_id'=> 2,
                'title' =>'Park View City Islamabad',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'Lahore-Islamabad Motorway M-2',
                'image' => 'Park-view-city-islamabad-project-title-img.jpg',
                'slug' => Str::slug('Park View City Islamabad'), 
                'description' => 'Park View City Islamabad',
                'excerpt' => 'Park View City Islamabad',
                'status' => 1,
                'is_active' => 1,
                'order' => 7,
                'project_type'=> 'commercial',
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => 'Park View City Islamabad',
                'meta_tag' => 'Park View City Islamabad',
                'meta_description' => 'Park View City Islamabad',

            ],
            [
                'project_id'=> 2,
                'title' =>'Zem Gardenia',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'Lahore-Islamabad Motorway M-2',
                'image' => 'Zem-gardenia-project-title-img islamabad.jpg',
                'slug' => Str::slug('Zem Gardenia'), 
                'description' => 'Zem Gardenia',
                'excerpt' => 'Zem Gardenia',
                'status' => 1,
                'is_active' => 0,
                'order' => 8,
                'project_type'=> 'commercial',
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => 'Zem Gardenia',
                'meta_tag' => 'Zem Gardenia',
                'meta_description' => 'Zem Gardenia',

            ],
            [
                'project_id'=> 2,
                'title' =>'Zem Ark',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'Lahore-Islamabad Motorway M-2',
                'image' => 'zem-ark-project-title-img islamabad.jpg',
                'slug' => Str::slug('Zem Ark'), 
                'description' => 'Zem Ark',
                'excerpt' => 'Zem Ark',
                'status' => 1,
                'is_active' => 0,
                'order' => 9,
                'project_type'=> 'commercial',
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => 'Zem Ark',
                'meta_tag' => 'Zem Ark',
                'meta_description' => 'Zem Ark',

            ],
            [
                'project_id'=> 2,
                'title' =>'Liberty Tower',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'Lahore-Islamabad Motorway M-2',
                'image' => 'Liberty-Tower-project-title-img islamabad.jpg',
                'slug' => Str::slug('Liberty Tower'), 
                'description' => 'Liberty Tower',
                'excerpt' => 'Liberty Tower',
                'status' => 1,
                'is_active' => 1,
                'order' => 10,
                'project_type'=> 'commercial',
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => 'Liberty Tower',
                'meta_tag' => 'Liberty Tower',
                'meta_description' => 'Liberty Tower',

            ],
            [
                'project_id'=> 2,
                'title' =>'Zem Insignia',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'Lahore-Islamabad Motorway M-2',
                'image' => 'zem-insignia-project-title-img islamabad.jpg',
                'slug' => Str::slug('Zem Insignia'), 
                'description' => 'Zem Insignia',
                'excerpt' => 'Zem Insignia',
                'status' => 1,
                'is_active' => 0,
                'order' => 11,
                'project_type'=> 'commercial',
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => 'Zem Insignia',
                'meta_tag' => 'Zem Insignia',
                'meta_description' => 'Zem Insignia',

            ],
            [
                'project_id'=> 2,
                'title' =>'Lake View Residencia',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'Lahore-Islamabad Motorway M-2',
                'image' => 'LVR-Title-Image_qkqtb7 residance islamabad.jpg',
                'slug' => Str::slug('Lake View Residencia'), 
                'description' => 'Lake View Residencia',
                'excerpt' => 'Lake View Residencia',
                'status' => 1,
                'is_active' => 1,
                'order' => 12,
                'project_type'=> 'commercial',
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => 'Lake View Residencia',
                'meta_tag' => 'Lake View Residencia',
                'meta_description' => 'Lake View Residencia',

            ],
            [
                'project_id'=> 2,
                'title' =>'Royal Swiss Hotel',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'Lahore-Islamabad Motorway M-2',
                'image' => 'royal swiss hotel islamabad.jpg',
                'slug' => Str::slug('Royal Swiss Hotel'), 
                'description' => 'Royal Swiss Hotel',
                'excerpt' => 'Royal Swiss Hotel',
                'status' => 1,
                'is_active' => 0,
                'order' => 13,
                'project_type'=> 'commercial',
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => 'Royal Swiss Hotel',
                'meta_tag' => 'Royal Swiss Hotel',
                'meta_description' => 'Royal Swiss Hotel',

            ],
            [
                'project_id'=> 2,
                'title' =>'Grand Millennium',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'Lahore-Islamabad Motorway M-2',
                'image' => 'grand islamabad.jpg',
                'slug' => Str::slug('Grand Millennium'), 
                'description' => 'Grand Millennium',
                'excerpt' => 'Grand Millennium',
                'status' => 1,
                'is_active' => 0,
                'order' => 14,
                'project_type'=> 'commercial',
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => 'Grand Millennium',
                'meta_tag' => 'Grand Millennium',
                'meta_description' => 'Grand Millennium',

            ],
            //ISLAMABAD projects

            //Sialkot projects
            [
                'project_id'=> 3,
                'title' =>'Model Safe City',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'Lahore-Islamabad Motorway M-2',
                'image' => 'model sialkot.jpg',
                'slug' => Str::slug('Model Safe City'), 
                'description' => 'Model Safe City',
                'excerpt' => 'Model Safe City',
                'status' => 1,
                'is_active' => 1,
                'order' => 1,
                'project_type'=> 'commercial',
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => 'Model Safe City',
                'meta_tag' => 'Model Safe City',
                'meta_description' => 'Model Safe City',

            ],
            [
                'project_id'=> 3,
                'title' =>'Main Market Domala',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'Lahore-Islamabad Motorway M-2',
                'image' => 'main-image sialkot.jpg',
                'slug' => Str::slug('Main Market Domala'), 
                'description' => 'Main Market Domala',
                'excerpt' => 'Main Market Domala',
                'status' => 1,
                'is_active' => 1,
                'order' => 2,
                'project_type'=> 'commercial',
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => 'Main Market Domala',
                'meta_tag' => 'Main Market Domala',
                'meta_description' => 'Main Market Domala',

            ],
            //End Sialkot projects

            //Peshawar projects

            //End Peshawar projects
            [
                'project_id'=> 4,
                'title' =>'Nova City',
                'price' =>'PKR 268,500 - 17,450,000',
                'address' =>'peshawar',
                'image' => 'novo peshawar.jpg',
                'slug' => Str::slug('Nova City peshawar'), 
                'description' => 'Nova City',
                'excerpt' => 'Nova City',
                'status' => 1,
                'is_active' => 1,
                'order' => 1,
                'project_type'=> 'commercial',
                'payment_plan' =>'paymentplan.pdf',
                'master_plan' =>'masterplan.pdf',
                'floor_plan' =>'floorplan.pdf',
                'meta_title' => 'Nova City',
                'meta_tag' => 'Nova City',
                'meta_description' => 'Nova City',

            ],
        ];
          

        foreach ($subProject as $pr) {
            SubProject::create($pr);
        }













    }
}
